### ISSUE TITLE
 No such file or directory

### ISSUE THREAD

**Issue by serdio-nerd** [dracula/gedit#10]
mv: cannot move 'dracula.xml' to '/home/user/.local/share/gedit/styles/': No such file or directory

**Comment by richin13** [comment]
Hello @serdio-nerd, after downloading the file `dracula.xml` can you confirm you're in the correct directory by using:

```bash
pwd
```
which should print the path where you downloaded the file to, if not, then `cd` into it (something like: `cd ~/Downloads`) before running `mv` 👍🏼 

----

Another alternative is to run:

```bash
cd ~/.local/share/gedit/styles/
wget https://raw.githubusercontent.com/dracula/gedit/master/dracula.xml
```

Which should also work

**Comment by richin13** [comment]
Let me know if you need further help here, closing for now!
