### ISSUE TITLE
Markdown not recognized

### ISSUE THREAD

**Issue by ghost** [dracula/gedit#11]
So, it appears after installing the theme, gedit doesn't appear to be using the theme correctly with Markdown files as it appears here:

![gedit](https://user-images.githubusercontent.com/19254816/137025033-760d9d5f-96c3-4b2f-8d84-523a6279ef37.png)

**Comment by richin13** [comment]
Hello! I can confirm I'm seeing the same behaviour, I'll check later this week what can we do about it 👍🏼 

Thanks for flagging this!

**Comment by zenorocha** [comment]
Any updates on this @richin13?
