### ISSUE TITLE
Dracula theme won't install on gedit version 46.1 and 46.2 (works for Gedit 45.0)

### ISSUE THREAD

**Issue by SpreadiesInSpace** [dracula/gedit#12]
> If you're reporting an UI issue, make sure you take a screenshot that shows the actual bug.
![Screenshot from 2024-04-16 01-27-22](https://github.com/dracula/gedit/assets/106583914/332e272c-a898-4427-9096-9db616634005)
![Screenshot from 2024-04-16 01-27-43](https://github.com/dracula/gedit/assets/106583914/a27a30e6-7b27-4a54-a2cb-5ef8b7da2b20)
![Screenshot from 2024-04-16 01-28-12](https://github.com/dracula/gedit/assets/106583914/f5aa1021-37e7-4610-a120-3ce02da41980)

**Comment by richin13** [comment]
Hello! Thanks for reporting! I've fixed the issue, can you try again?

**Comment by SpreadiesInSpace** [comment]
Confirmed working on 46.2
![Screenshot from 2024-04-18 00-23-26](https://github.com/dracula/gedit/assets/106583914/27731b23-3933-4ead-a18d-80353b54dc69)

**Comment by SpreadiesInSpace** [comment]
Update, this works on Gedit 46, but distributions with older versions of gedit like Fedora 39 (gedit 45) and Debian (gedit 44) no longer work. I saw the commit, perhaps have 2 versions?

**Comment by richin13** [comment]
Gotchu, welp that's very annoying (gedit making weird non-compatible updates 😅)

I'll split it into two files in the meantime, thanks for checking 👍🏼

**Comment by chergert** [comment]
I just want to point out that `"kind"` is not a thing in GtkSourceView. It sounds like maybe this is using a fork of GtkSourceView which supports "kind". Upstream, in GtkSourceView, we use "metadata" tags for light/dark and specifying the alternates supported.
