### ISSUE TITLE
Dracula theme won't install on gedit version 48 - GNOME version 47

### ISSUE THREAD

**Issue by laamalif** [dracula/gedit#15]
> If you're reporting an UI issue, make sure you take a screenshot that shows the actual bug.
![gedit](https://github.com/user-attachments/assets/29dc5cbc-f500-49cc-a596-d24f42e7f162)

**Comment by josesj** [comment]
Change install path to $HOME/.local/share/libgedit-gtksourceview-300/styles

**Comment by laamalif** [comment]
Please update the main documentation.
