### ISSUE TITLE
def:function style is duplicated in the theme code

### ISSUE THREAD

**Issue by lmintmate** [dracula/gedit#6]
Said style definition is present on both lines 60 and 67 of the code. This duplication doesn't affect the theme adversely for the moment, since both lines are exactly the same, but it would be best if it were removed, as to avoid any potential issues in the future (and removing it from the code doesn't affect the theme adversely either - I did it already to the file on my own system).
Thanks in advance for understanding.

**Comment by richin13** [comment]
Thank you @lmintmate, it was fixed in https://github.com/dracula/gedit/commit/f67b9a6f23ff8ff08407ab6cc5a4dd638f2e9274
